Add basic web target support to vscode config in init projects
orx/orx pull request #116
Opened 2024-12-27 16:14 UTC by hcarty

Tested on macOS by creating a fresh `init` project from this branch, opening the project in vscode, choosing the `Run [name] (web)` task and the game built, `emrun` started, and the game popped up in a browser tab.

I'm not sure if tasks can be defined as dependent on a particular tool existing like `emcc`, so this will always provide web build and run targets even if the user does not have the necessary emsdk tooling locally.

2024-12-30 23:30 UTC, iarwain requested changes

2024-12-31 06:33 UTC, hcarty commented on code/build/template/.vscode/tasks.json
> +        "Build [name] (profile)"
This is the dependency for the profile build - the web build dependence on the release build is earlier in the file: https://github.com/orx/orx/pull/116/files#diff-ffa7ce2814514f9c654147f50633b350156698bd410ab89d9a52eab3e3031262R121

2024-12-31 08:14 UTC, sausagejohnson commented on code/build/template/.vscode/tasks.json
> +        "command": "make -j config=releaseweb"
Everywhere only where emake is installed though?

2024-12-31 10:12 UTC, iarwain commented on code/build/template/.vscode/tasks.json
> +        "command": "make -j config=releaseweb"
`emmake` is part of `empscripten`, which is required to build the web target, so it will be available by definition. :)

2024-12-31 14:46 UTC, hcarty commented on code/build/template/.vscode/tasks.json
> +        "command": "make -j config=releaseweb"
Change made - all three platforms should use `emmake` now!

2024-12-31 14:57 UTC, iarwain commented on code/build/template/.vscode/tasks.json
> +        "command": "make -j config=releaseweb"
Thanks!

2024-12-31 14:58 UTC, iarwain approved these changes

2024-12-31 14:58 UTC, merged